version: 2

run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign

linters-settings:
  gocyclo:
    min-complexity: 15

  errcheck:
    check-type-assertions: true

  revive:
    severity: warning
    rules:
      - name: indent-error-flow

issues:
  exclude-use-default: false
  exclude-dirs:
    - config
    - sql
